### ISSUE TITLE
metaData field not storing info

### ISSUE THREAD

**Issue by tijs** [mopinion/mopinion-sdk-react-native#12]
I have just added the metaData field to our react-native deployment. While the data is there:

`{"appVersion": "6.8.0", "brand": "ad", "consentString": "functional|analytics|content_recommendation|targeted_advertising|social_media", "loggedIn": "NOT_LOGGED_IN", "osVersion": "13.3", "platform": "ios", "privacyUUID": "803B9175-CEFC-4831-9D64-158C60043712"}`

These custom meta data fields are not visible in the feedback form on your website nor are they present in the downloadable feedback results. In fact; if i add the metaData field to a form the existing metaData fields for OS and 'browser agent' are empty so i now have less info instead of more.

Please look into this as we do need extra meta information especially to be able to respond to technical feedback.

**Comment by GustaafL** [comment]
Hi Tijs,

The browser and OS data can take some time to be processed. We will investigate the issue with the metadata and let you know when more information is available.

Kind regards,
Guus

**Comment by Anwardo** [comment]
It seems the webview implementation wasn't passing along the metadata to the form yet. We just released a version in which it does.
