### ISSUE TITLE
How to get percentage, visitors, etc ?

### ISSUE THREAD

**Issue by manuelabarca** [mopinion/mopinion-sdk-react-native#13]
Just see logs, for examples:
"Checking condition -- etc..."
"Checking percentage -- etc.."

**Comment by Anwardo** [comment]
What exactly do you want to get here? Those logs are related to your deployment settings which you can setup inside the deployment editor in our platform. These values aren't meant to be accessed outside of our component.

**Comment by stevenkuipers** [comment]
I'm closing this issue for now. 

@manuelabarca if you feel like this issue should stay open could you explain what is that you want to do here?
