### ISSUE TITLE
Delay opening feedback form on Android

### ISSUE THREAD

**Issue by tijs** [mopinion/mopinion-sdk-react-native#14]
As a user you want the feedback form (modal) to open instantly when you tap the feedback button. With the iOS implementation this is the case. For Android however it takes 2-3 seconds between tapping the feedback button (triggering the open event) and the modal with the feedback form opening. 

For most users the feedback button thus will appear broken.

I'm assuming the delay is caused because the feedback form content has to be loaded before the form opens. An acceptable solution would be to show the modal instantly but then show a loader while the feedback form content loads. That way the user will have (UI) feedback that's something is happening.

**Comment by Anwardo** [comment]
I can't seem to replicate this issue. It could be related to your implementation. 

I believe based on our earlier conversations you're not rendering the `MopinionDeployment` component until you want the form to show right? It seems like this issue might be resolved if you always render the `MopinionDeployment` component so the actual deployment is already fetched and checked. (It wont actually render anything until a form should show). 

The implementation would look something like this

```
import { MopinionDeployment } from 'mopinion-react-native-sdk';

function App() {
  return (
    <View>
      {
        //...main app content
      }
      <MopinionDeployment deploymentID={'123abc'}  />
    </View>
  )
}
```


```
import { MopinionSDK } from 'mopinion-react-native-sdk';

function Screen() {
  return (
     <View>
      {
        //...screen content
      }
      <Button
        onPress={() => MopinionSDK.event(`${YOUR_EVENT}`)}
      >
        Feedback
      </Button>
    </View>
  )
}
```  

We can't render the feedback modal yet if we don't know for sure a form should actually be shown based on the checked deployment rules.

**Comment by tijs** [comment]
Ok thanks, i'll give that a shot and close the issue if it indeed resolves this problem.

**Comment by tijs** [comment]
This was indeed fixed by 'preloading' the component
