### ISSUE TITLE
Form not fully aligned to Motorola One

### ISSUE THREAD

**Issue by rrutkowski** [mopinion/mopinion-sdk-react-native#17]
While testing on Motorla One physical device (720 x 1520 pixels, 19:9 ratio, Android 10) the form was not properly aligned to the screen. Printscreens attached. 
![Screenshot_20200624-132811](https://user-images.githubusercontent.com/47834306/85556364-0f9abb80-b627-11ea-9a33-0bd4767cdd40.png)
![Screenshot_20200624-141353](https://user-images.githubusercontent.com/47834306/85556371-10cbe880-b627-11ea-823c-c5879b0b7f7c.png)

**Comment by Piethot** [comment]
Hi @rrutkowski, thanks for reporting this issue. We will investigate and get back to you on this issue. Kind regards, Pieter

**Comment by stevenkuipers** [comment]
Hi @rrutkowski ,

We found one way to recreate similar behaviour in my simulator, but it’s unrelated to the phone. Where did you place the <MopinionDeployment> element? It should be at App level. The view where this element is placed in will serve as the root view element for the feedback form. If that root view element is less tall than the display and has a fixed size, so will the feedback form be.  Also, please check the style of the element containing the MopinionDeployment element. Is it flexbox or fixed size?

If this does not resolve this issue for you, could you then tell us what version of the react-native SDK you are using and what version of react-native? Does this happen when you use the standard 3 button “Android Navigation Bar”?
