### ISSUE TITLE
react-native-material-textfield dependency outdated

### ISSUE THREAD

**Issue by tijs** [mopinion/mopinion-sdk-react-native#18]
When we upgrade to the latest react-native types (@types/react-native) we start getting type errors in the sub dependency for the mopinion package: react-native-material-textfield. It looks like there is no new version enabled so perhaps an alternative should be found to prevent further upgrades of react-native projects using mopinion from being impossible.

We can hold of the types upgrade for now but at some point we would like to move to the latest version.

**Comment by Piethot** [comment]
Hi Thijs, we will create a workaround so this component won't prevent you from further upgrading. We will let you know when it is available.

**Comment by PaulvanMotman** [comment]
Hi Piethot, I'm also running into this issue with the latest React Native version. Will the workaround be available soon?

**Comment by stevenkuipers** [comment]
Hi Paul, Tijs.

We are working on a new version of the SDK where this issue will be addressed, we expect to release this early next week.

The updated versions for the dependencies are as follows:
"@mopinion-mobile/react-native-material-dropdown": "^1.0.0",
"@ubaids/react-native-material-textfield": "^0.16.3,
"create-react-class": "^15.6.3"

These work with rn 0.61.5.  As a workaround, until the update is live, you might want to manually update/add these dependencies to prevent these errors.

**Comment by GustaafL** [comment]
Hi Paul and Tijs,

Thank you for making us aware of this issue. The new version 1.3.0 of the mopinion-react-native-sdk has now been released. This fixes the dependency issues of the react-native-material-textfield.

**Comment by PaulvanMotman** [comment]
Thank you GustaafL and stevenkuipers, can confirm there are no more dependency issues.
