### ISSUE TITLE
[Android] Invalid background color for unselected radio buttons

### ISSUE THREAD

**Issue by Anno008** [mopinion/mopinion-sdk-react-native#2]
### Description
Only on Android the unselected radio buttons background is always dark blue (should be white).

### Steps to Reproduce
* Open the mopinion form
* Reach the first page (in our case) that gives us radio buttons

### Actual Behavior
When nothing is selected all radio buttons have a dark blue background. When we select an item it has light blue background while the other items still have the dark blue, kinda tricky to tell what is selected and what isn't.

### Expected Behavior
Only the selected item should have blue background while the rest should have white, like on iOS.

### Basic Information
Version with issue: 0.3.1
React Native Version: 0.59.3
React Version: 16.8.6

### Screenshots
With no selection
![NothingSelected](https://user-images.githubusercontent.com/26136098/57223457-6b128000-7006-11e9-9443-d5ee52279aeb.png)
First item selected
![SelectedOption1](https://user-images.githubusercontent.com/26136098/57223478-81204080-7006-11e9-8b76-2874ec5bb213.png)

**Comment by Anwardo** [comment]
Fixed in 0.3.3!
