### ISSUE TITLE
Allow configurable animations or no animations

### ISSUE THREAD

**Issue by tijs** [mopinion/mopinion-sdk-react-native#22]
We would love to be able to have more control over the animation used when opening the feedback modal. For instance the ability to turn off the slide up animation completely and provide our own in a custom container.

**Comment by Anwardo** [comment]
We had an undocumented prop for this already, we just released version 1.4.0 where added it to the documentation. 

You can use the `modalAnimationDuration` prop to customize the animation duration of the dialog. Set it to `0` to disable the animation.

```
<MopinionDeployment
  {...otherProps}
  modalAnimationDuration={0}
/>
```
