### ISSUE TITLE
Feedback not saved if a metadata value is undefined

### ISSUE THREAD

**Issue by SpreadTriad** [mopinion/mopinion-sdk-react-native#23]
#### Issue description

With version 1.4.0: it seems that, if any of the properties in the metadata object is undefined, the form does not save at all.

It's easy to make a workaround, but would be nice to fix it, since it's not immediately clear what the cause is.

#### Steps to reproduce the issue

Add an undefined value in the metadata object and send a form

<MopinionDeployment
    deploymentID="MY_ID"
    metaData={{
        customerId: undefined,
    }}
/>

#### What's the actual result?

The back end returns an error and no data is stored at all. The response of the POST is:

{"code":666,"error":"unknown error"} 

#### What's the expected result?

I would expect the back end to be able to handle undefined values, or barring that, at least return sensible feedback message or add this caveat to the documentation.

**Comment by Anwardo** [comment]
@SpreadTriad thanks for the detailed report. We just released version 2.0.0 where we catch possible null or undefined values when posting the feedback and transform them to an empty string to mitigate this issue.
