### ISSUE TITLE
React native MopinionSDK.event('_proactive') is not opening the form

### ISSUE THREAD

**Issue by rkenfack** [mopinion/mopinion-sdk-react-native#28]
I am trying to integrate mopinion react native SDK to our app, but it's not working as expected.
This is what i am doing.

`<MopinionDeployment deploymentID={deployementKey} />`

and later on i trigger the event like `MopinionSDK.event('_proactive')` since the trigger is 'proactive'.

To make it work i have to trigger the event returned when the deployement is fetched
`MopinionSDK.event('_force_formkey')` but i don't think that this is how it should be.

**Comment by mopinion-support** [comment]
Hi @rkenfack, thanks for your comment and sorry for our late reply. We will look into the issue and come back to you as soon as possible. Kind regards, Pieter
