### ISSUE TITLE
[Android] Unable to press continue button after pressing OK on the keyboard

### ISSUE THREAD

**Issue by Anno008** [mopinion/mopinion-sdk-react-native#3]
### Steps to Reproduce
* Open the mopinion form
* Reach the page that gives the option to provide our contact details.
* Fill the email field. (we put test@test.com)
* Press the OK button on the keyboard

### Actual Behavior
When we press the ok button, the mopinion form goes down a little bit, we can see the original screen behind it. Moreover, the continue button goes out of reach, can't scroll down to it.

### Expected Behavior
The form shouldn't be moved down.
Pressing the OK button on the keyboard should:
1. Dismiss the keyboard?
2. Focus the next input field, phone number?
3. Press the continue button?

### Basic Information
Version with issue: 0.3.1
React Native Version: 0.59.3
React Version: 16.8.6

### Screenshots
Before pressing the OK button on the keyboard:
![BeforePressingOK](https://user-images.githubusercontent.com/26136098/57224441-c7c36a00-7009-11e9-99a3-61906a88336a.png)

After pressing the OK button on the keyboard:
![AfterPressingOK](https://user-images.githubusercontent.com/26136098/57224471-df025780-7009-11e9-9e1e-b2bf9ac6966b.png)

**Comment by keeswolters** [comment]
Hi @Anno008, thanks for reaching out to us. Can you please email your organisation name or mopinion  username to support@mopinion.com, so we can also have a look at your form configuration etc?

**Comment by Anwardo** [comment]
I wasn't able to replicate the issue with the entire form dialog scrolling down. We have improved the detection of the appearance of the keyboard though in version 0.3.3. We're now using the `keyboardDidShow` and `keyboardDidHide` events where previously we used  `keyboardWillShow` and `keyboardWillHide` which don't always work in Android. This should mean the continue button should always stay accessible.

Leaving this open for now till we reach a full resolution.

**Comment by ledbat** [comment]
Hi there,
We (Talpa) are encountering a similar issue.
When typing and the keyboard is expanded, when pressing the Send button the screen wil close halve way. See video Attached.

We use the latest version: 0.33
[20190517-083752-480x986.mp4.zip](https://github.com/mopinion/mopinion-sdk-react-native/files/3190193/20190517-083752-480x986.mp4.zip)

**Comment by tijs** [comment]
@Anwardo i am experiencing a similar issue. Everything works fine on iOS. On Android however:

- when the any input field is tapped that triggers the keyboard the keyboard pushes the form out of view

![Screenshot_20200106-135856_AD Test debug](https://user-images.githubusercontent.com/3108/71819766-3bcc7b00-308d-11ea-89f1-1b0046642b83.jpg)

- when you 'close' the keyboard (down arrow) the whole modal moves down instead of just the keyboard

![Screenshot_20200106-135935_AD Test debug](https://user-images.githubusercontent.com/3108/71819769-438c1f80-308d-11ea-93a3-d4f4154e6e16.jpg)

Above screenshots are from a Samsung S9 device.

**Comment by tijs** [comment]
This on the latest 1.2.0 version btw.

**Comment by Anwardo** [comment]
We just released v1.2.1 with a fix for this issue 🚀 🙂
