### ISSUE TITLE
SDK not working with react native 0.69

### ISSUE THREAD

**Issue by jimbofoo** [mopinion/mopinion-sdk-react-native#35]
TypeError: undefined is not an object (evaluating '_reactNative.Text.propTypes.style')

ViewPropTypes are no longer available.

**Comment by mopinion-support** [comment]
Thanks @jimbofoo for letting us know. We will investigate and keep you updated.

**Comment by mopinion-support** [comment]
@jimbofoo can you tell us which version of our SDK you are using? As this issue should not occur with our latest version of the SDK.

**Comment by jimbofoo** [comment]
Using 2.1.0, I think the issue is here:
https://github.com/mopinion/mopinion-sdk-react-native/blob/master/components/Dropdown/src/components/dropdown/index.js

Where ViewPropTypes is imported

**Comment by burnsting** [comment]
We're having a similar issue blocking us from upgrading to RN 0.69.5 (using 2.1.0 as well).

`Error: Requiring module "node_modules/mopinion-react-native-sdk/components/TextField/index.js", which threw an exception: TypeError: Cannot read property 'style' of undefined`

It's not clear to me which style is undefined however (there are so many). Any ideas?

**Comment by burnsting** [comment]
Found the issue with deprecated Text.propTypes.

I've created a PR here: https://github.com/mopinion/mopinion-sdk-react-native/pull/37

**Comment by Piethot** [comment]
Thanks @burnsting . This issue is fixed in 2.1.1 - just released.
