### ISSUE TITLE
[iOS] Wrap the form in SafeAreaView to avoid notches on IPhoneX devices

### ISSUE THREAD

**Issue by Anno008** [mopinion/mopinion-sdk-react-native#5]
### Steps to Reproduce
* Open the mopinion form

### Actual Behavior
On certain devices (IPhone X, IPhone XR, ...) where we have notches, home bar, rounded corners... The form goes behind them, i.e. is cut off by them.

### Expected Behavior
The header of the form shouldn't be cut by the top notch it should have appropriate padding. Furthermore, the form shouldn't go behind the home bar, but have an appropriate spacing.
Could we perhaps wrap the form into SafeAreaView to accomplish this?

### Basic Information
Version with issue: 0.3.1
React Native Version: 0.59.3
React Version: 16.8.6
Devices: Any from the IPhone X family

### Screenshots
Top:
![Header](https://user-images.githubusercontent.com/26136098/57227851-a7e47400-7012-11e9-9abf-23df8fcbd742.png)

Bottom:
![HomeBar](https://user-images.githubusercontent.com/26136098/57227860-b03caf00-7012-11e9-9122-e2444c76638d.png)

**Comment by Anwardo** [comment]
@Anno008 thanks for your detailed description! We just fixed this issue in version 0.3.3. We're now utilizing SafeAreaView to only render content in the safe area.
