### ISSUE TITLE
Migrate rnpm setup

### ISSUE THREAD

**Issue by tijs** [mopinion/mopinion-sdk-react-native#7]
We are currently evaluating Mopinion and the react-native sdk you offer. One of the things we noticed it that you are still using a since deprecated rnpm config leading to the following warning:

```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - mopinion-react-native-sdk: https://github.com/mopinion/mopinion-sdk-react-native#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
```

Should be an easy fix, in fact it seems like this issue (and several others) are already resolved in a current incoming PR, would be great if that could be merged! https://github.com/mopinion/mopinion-sdk-react-native/pull/6

**Comment by Anwardo** [comment]
Hi, thanks for you feedback!  🙂 We just merged #6 which indeed resolves this issue. Expect a new release next week.

**Comment by tijs** [comment]
@Anwardo would you mind making a new release as well?

https://www.npmjs.com/package/mopinion-react-native-sdk

I would prefer not to use the master branch in my project..

**Comment by Anwardo** [comment]
@tijs sorry about the delay! We just wanted to make sure we had everything thoroughly tested and could provide proper instructions for installing/upgrading. Testing has been concluded the new package will be available tomorrow!

**Comment by Anwardo** [comment]
The new package has been released!

**Comment by tijs** [comment]
Great news, will try it out today
